### ISSUE TITLE
Validating issue 

### ISSUE THREAD

**Issue by haribalaram** [kickboxio/kickbox-node#10]
Hi, Team

i am new to Kickbox.io in Node.js

i am trying to validate the email address with is deliverable or un-deliverable. but when i give the wrong email address it showing as deliverable (test@test.123.com) there is no email address like but it showing as deliverable. 

kindly find the Code attached with this which we have used.
![kickboxcode](https://cloud.githubusercontent.com/assets/22980352/19597438/3cf4ead4-97b2-11e6-9124-a4c0e6ea3d7c.png)

kindly find the attached file for the test result. 
![kickbox](https://cloud.githubusercontent.com/assets/22980352/19597395/dcc5e7f8-97b1-11e6-8601-1f7d3ae5b7d9.png)

kindly check and let us know if we miss anything.

**Comment by danhstevens** [comment]
Hi @haribalaram! Are you by chance using the [Sandbox API](http://docs.kickbox.io/docs/sandbox-api)? This will always return Deliverable unless you use the specified keywords. A production API key will generate true production results (but will deduct from your verification credit balance). Let me know if that helps!
