### ISSUE TITLE
Can you check is this emails disposable?

### ISSUE THREAD

**Issue by topilski** [kickboxio/kickbox-node#12]
Hi i don't know where i should post this issue but i think domains: emailna.co and xvx.us is disposable.

**Comment by danhstevens** [comment]
Hi @topilski - vxv.us doesn't seem to have any MX records nor accept email on its A records. It might have been a disposable domain at some point but doesn't appear to be currently.

emailna.co - that's a great catch. I've confirmed that's an active disposable domain and will be adding it within the next hour.

Here is the open source repo where we maintain disposable email domains: https://github.com/ivolo/disposable-email-domains - you should see your suggestion arrive there shortly.

Thanks!
