### ISSUE TITLE
Passing API key on call (Feature request)

### ISSUE THREAD

**Issue by GHNewbiee** [kickboxio/kickbox-node#13]
Hi,

There are cases (for example: a (micro)service which provides access to different local clients/keys into your service) in which the API key may not be known from the beginning and is taken after querying a database. In this case, it would be more convenient if the key was passed later as an option (with timeout) during the call and not on declaration through `require`.

Tia

**Comment by rohan2734** [comment]
same feature is requested from my side too

**Comment by danhstevens** [comment]
This can be done currently. Example:

```javascript
var kickbox = require('kickbox');
// ...
var client1 = kickbox.client('Your_API_Key_Here').kickbox();
var client2 = kickbox.client('Your_API_Key_Here').kickbox();
// etc
```
