### ISSUE TITLE
Sandbox example results in HTTP 403 then next request 500

### ISSUE THREAD

**Issue by odnarb** [kickboxio/kickbox-node#3]
When using the sanbox API key and test email for insufficient balance a 403 is returned as expected from the API, but then any following email always results in an HTTP 500 but ones after the 500 then result in normal operation.

``` js
var emails = [
    "donna+unavailable-smtp@example.com",
    "marsha+no-connect@example.com",
    "henry+insufficient-balance@example.com",
    "alter_ego+role@example.com",
    "avenger+role@example.com",
];
kickbox.verify(emails[index_checked], function (err,response) {
    if(err){
        console.log("error caught");
    } 
    if (response && response.body) {
        console.log("we have a response and thus no error");
        console.log(response.body);
    }
});
```

Any email at the end of the array will result in an error 500, so "avenger+role@example.com" will be the error 500 in this example.

Is this supposed to happen?

I was expecting something like it would allow all requests through even if the prior resulted in a 4xx. I understand failing the kickbox npm client if there was an actual 5xx but this seems like the http client behavior is altered to disallow further requests after the 403 (and really, do a "throw err" instead of what I did here in this example.).. I just don't think semantically this is right.

Can you look into this?
Thanks

**Comment by geoffreak** [comment]
Thanks for bringing this to our attention. Due to a bug in our system, the `insufficient-balance` test request is issuing a 500 status code instead of a 403. We should be rolling out a fix shortly to address this. 

In regards to the other emails after that one also returning a 500 error, we can't seem to replicate that. There may be something outside of the code sample you provided that is causing this issue.

**Comment by odnarb** [comment]
Thanks for the update. I'll be using the request npm until this is fixed.

**Comment by odnarb** [comment]
Oh, I see what you mean.. I just tried npm request.. the issue is in in the actual API and not the npm package.

Yea, disregard the other stuff in the issue report.

**Comment by geoffreak** [comment]
That request should now be returning a 403 response code. Try your code again now and see how things go.

**Comment by odnarb** [comment]
Excellent, works. Did not have to change/update kickbox package.
